### ISSUE TITLE
[UI] Add to the list of applications the application output

### ISSUE THREAD

**Issue by ATomkivEX** [JovianX/Service-Hub#249]

**Comment by rtpro** [comment]
In the list of apps page `/applications`:

*   [ ] Make `Create At` date show only the date(without the time), show full date on hover
*   [ ] Move reversion to be part of the Template name  - ie `<App> [Rev #]`  (It should not have its own column)
*   [ ] Make the output field wider 

In the app page

*    [ ]  The table should be the same as it is in the list (There are missing fields)
*    [ ]  Add an "Application" tab before the events tab
    *   [ ] The application tab should have Inputs and outputs, similar to Helm release details 

![](https://user-images.githubusercontent.com/2787296/214003494-b0f6f723-670f-4eeb-bf72-820a873d363c.png)

**Comment by rtpro** [comment]
In the list of apps page `/applications`:

*   [ ] Make `Create At` date show only the date(without the time), show full date on hover
*   [ ] Move reversion to be part of the Template name  - ie `<App> [Rev #]`  (It should not have its own column)
*   [ ] Make the output field wider 

In the app page

*    [ ]  The table should be the same as it is in the list (There are missing fields)
*    [ ]  Add an "Application" tab before the events tab
    *   [ ] The application tab should have Inputs and outputs, similar to Helm release details 

![](https://user-images.githubusercontent.com/2787296/214003494-b0f6f723-670f-4eeb-bf72-820a873d363c.png)
